export const SITE_NAME = "My Compu Clinic"
export const SITE_URL = "https://evolve8.vercel.app/"
export const SITE_DESCRIPTION = "Manufacturer, Wholesaler & Exporter of Jute bags, Cotton Bag for Corporate Events & Exhibitions"
export const SITE_KEYWORDS = "Jute bags, Cotton Bag, Canvas Bags, File Folders, Denim Bags, Pouches"
export const SITE_CATEGORY = "Shopping"
export const SITE_IMAGE = "https://www.oxabags.com/og.webp"
export const OWNER_NAME = "Owner Name"
export const OWNER_EMAIL = "info@mycompuclinic.com"
export const OWNER_PHONE_1 = "#"
export const OWNER_PHONE_2 = "#"
export const COMPANY_NAME = "MyCompuClinic"
export const COMPANY_ADDRESS = "Ahmedabad, India"

